import { Content } from './types';

// The TMDB API Key is now managed in the Admin Panel's Settings page.
// You can set an initial key there. It will be stored in local storage.

// Content is now sourced from this local array.
export const CONTENT: Content[] = [
  {
    id: 1,
    created_at: '2024-07-29T10:00:00Z',
    contentType: 'Movie',
    title: 'Dune: Part Two (2024)',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    releaseDate: 'March 1, 2024',
    quality: 'Blu-Ray',
    genres: ['Science Fiction', 'Adventure'],
    downloadSections: [{ title: '{ English 5.1 & Hindi 5.1 }', links: [{ provider: 'G-Direct', url: '#', type: 'G-Direct [Instant]', size: '1.2GB' }] }],
  },
  {
    id: 2,
    created_at: '2024-07-28T11:00:00Z',
    contentType: 'Web Series',
    title: 'The Boys (2019)',
    description: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/2zmTngn1tJ9p5PaB2S_M3SjC_rQ.jpg',
    releaseDate: 'July 26, 2019',
    quality: 'WEB-DL',
    genres: ['Action', 'Comedy', 'Crime'],
    downloadSections: [{ title: 'Season 1-3 Zip { English 5.1 & Hindi 5.1 }', links: [{ provider: 'Batch/Zip', url: '#', type: 'Batch/Zip', size: '15GB' }] }],
  },
  {
    id: 3,
    created_at: '2024-07-27T12:00:00Z',
    contentType: 'Movie',
    title: 'Oppenheimer (2023)',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    releaseDate: 'July 21, 2023',
    quality: 'Blu-Ray',
    genres: ['Biography', 'Drama', 'History'],
  },
  {
    id: 4,
    created_at: '2024-07-26T13:00:00Z',
    contentType: 'Movie',
    title: 'Godzilla x Kong: The New Empire (2024)',
    description: 'Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island\'s mysteries.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tMefBSflR6PGsBKJCweax7J69J2.jpg',
    releaseDate: 'March 29, 2024',
    quality: 'WEB-DL',
    genres: ['Action', 'Science Fiction', 'Adventure'],
  },
  {
    id: 5,
    created_at: '2024-07-25T14:00:00Z',
    contentType: 'Web Series',
    title: 'Stranger Things (2016)',
    description: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    releaseDate: 'July 15, 2016',
    quality: 'WEB-DL',
    genres: ['Drama', 'Fantasy', 'Horror'],
  },
  {
    id: 6,
    created_at: '2024-07-24T15:00:00Z',
    contentType: 'Movie',
    title: 'Interstellar (2014)',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    releaseDate: 'November 5, 2014',
    quality: 'Blu-Ray',
    genres: ['Adventure', 'Drama', 'Science Fiction'],
  },
  {
    id: 7,
    created_at: '2024-07-23T16:00:00Z',
    contentType: 'Movie',
    title: 'The Dark Knight (2008)',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    releaseDate: 'July 18, 2008',
    quality: 'Blu-Ray',
    genres: ['Action', 'Crime', 'Drama'],
  },
  {
    id: 8,
    created_at: '2024-07-22T17:00:00Z',
    contentType: 'Web Series',
    title: 'Game of Thrones (2011)',
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1XS1oqL89wqnsAbjSOe94xRJllh.jpg',
    releaseDate: 'April 17, 2011',
    quality: 'WEB-DL',
    genres: ['Sci-Fi & Fantasy', 'Drama', 'Action & Adventure'],
  },
  {
    id: 9,
    created_at: '2024-07-21T18:00:00Z',
    contentType: 'Movie',
    title: 'Parasite (2019)',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    releaseDate: 'May 30, 2019',
    quality: 'Blu-Ray',
    genres: ['Comedy', 'Thriller', 'Drama'],
  },
  {
    id: 10,
    created_at: '2024-07-20T19:00:00Z',
    contentType: 'Web Series',
    title: 'Breaking Bad (2008)',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    releaseDate: 'January 20, 2008',
    quality: 'Blu-Ray',
    genres: ['Drama', 'Crime'],
  },
  {
    id: 11,
    created_at: '2024-07-19T20:00:00Z',
    contentType: 'Movie',
    title: 'Pulp Fiction (1994)',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    releaseDate: 'October 14, 1994',
    quality: 'Blu-Ray',
    genres: ['Thriller', 'Crime'],
  },
  {
    id: 12,
    created_at: '2024-07-18T21:00:00Z',
    contentType: 'Movie',
    title: 'Forrest Gump (1994)',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    releaseDate: 'July 6, 1994',
    quality: 'Blu-Ray',
    genres: ['Comedy', 'Drama', 'Romance'],
  },
  {
    id: 13,
    created_at: '2024-07-17T22:00:00Z',
    contentType: 'Movie',
    title: 'The Matrix (1999)',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89JxwIhLQg3r3MFy5A1g2G1pyS.jpg',
    releaseDate: 'March 31, 1999',
    quality: 'Blu-Ray',
    genres: ['Action', 'Science Fiction'],
  },
];
