
import { createClient } from '@supabase/supabase-js';

// IMPORTANT: Replace with your actual Supabase project URL and anon key.
// You can find these in your Supabase project settings under "API".
const supabaseUrl = 'https://xnvocqdsxbcripjrwaqq.supabase.co'; // Replace with your URL
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhudm9jcWRzeGJjcmlwanJ3YXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTg2ODAsImV4cCI6MjA3NzQ3NDY4MH0.Nca-kn5Q6itEAIWxBsHPXbzkJmrCDvM7pylqcpjZEIs'; // Replace with your anon key

// A simple check to ensure the user has updated the credentials.
if (supabaseUrl.includes('your-project-id') || supabaseAnonKey.includes('your-anon-key')) {
  const warningMessage = `
    ********************************************************************************
    * WARNING: Supabase credentials are not set!                                   *
    *                                                                              *
    * Please open 'lib/supabaseClient.ts' and replace the placeholder values for   *
    * 'supabaseUrl' and 'supabaseAnonKey' with your actual Supabase credentials.   *
    *                                                                              *
    * You also need to create a 'content' table in your Supabase project.          *
    * Go to the SQL Editor in your Supabase dashboard and run the following SQL:   *
    *                                                                              *
    * CREATE TABLE public.content (                                               *
    *   id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,                      *
    *   created_at timestamp with time zone NOT NULL DEFAULT now(),                *
    *   content_type text NOT NULL,                                                *
    *   title text NOT NULL,                                                        *
    *   description text NOT NULL,                                                  *
    *   poster_url text NOT NULL,                                                    *
    *   release_date text NOT NULL,                                                  *
    *   quality text NOT NULL,                                                      *
    *   genres text[] NOT NULL,                                                      *
    *   download_sections jsonb,                                                     *
    *   CONSTRAINT content_pkey PRIMARY KEY (id)                                     *
    * );                                                                             *
    ********************************************************************************
  `;
  console.warn(warningMessage);
}


export const supabase = createClient(supabaseUrl, supabaseAnonKey);